sonata_admin:
    title: 'Portfolio Admin'
    templates:
        layout:  '/admin/layout.html.twig'
        user_block: '/admin/blocks/user_block.html.twig'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            Default:
                label:                Default
                label_catalogue:      ~
                items:
                - admin.project
                - admin.user

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
