Project:
  type: object
  config:
    fields:
      id:
        type: Int
      title:
        type: String
      content:
        type: String
      status:
        type: Boolean
      image:
        type: String

